### ISSUE TITLE
Integration of QTLab

### ISSUE THREAD

**Issue by lumip** [qutech/qupulse#11]
"QTLab is an IPython-based measurement environment. It contains drivers for many instruments and integrates data plotting using gnuplot. Although it is mainly intended to perform automated measurements by creating Python scripts, an extensive set of GTK+-based GUI components is also included, for example to show the current instrument state and to perform simple tasks and measurements." -- http://qtlab.sourceforge.net/

QTLab might provide an existing implementation for hardware abstraction and basic experiment/measurement execution. It is also already employed by several research groups (according to @hbluhm ). Integrating it as far as possible into the qc-toolkit seems desirable.

To this aim, it must be evaluated, to which extent QTLab can be reused and integrated.

The current source code can be found at: http://www.github.com/heeres/qtlab

**Comment by hbluhm** [comment]
Copenhagen is developing a successor to QTLab called QCodes. A glimpse of it looks interesting. A testing release might become available in fall 2016. It is supported by Microsoft and eventually  supposed to become open source. I would like us to first think about a general interface to acquisition packages (See also #9).

**Comment by terrorfisch** [comment]
The measurement framework integration is not implemented in qupulse. We want to provide tools for easy integration.
