### ISSUE TITLE
Sequencing: Same Template Generates Multiple Waveforms

### ISSUE THREAD

**Issue by lumip** [qutech/qupulse#112]
It seems that during the sequencing process, if a template is translated multiple times, it generates multiple identical waveforms instead of providing the same waveform object multiple times. There should be a caching mechanism somewhere (in Sequencer?). Investigate.

**Comment by terrorfisch** [comment]
The waveforms iare not sampled at this point, so the memory wasted on the machine is probably not worth the effort. The above assumes that the AWG driver which samples the waveform will detect the duplicates.

**Comment by terrorfisch** [comment]
Improving this is AWG specific and an ongoing effort.
