### ISSUE TITLE
Hardware Abstraction

### ISSUE THREAD

**Issue by lumip** [qutech/qupulse#12]
Hardware qubits are controlled using voltage signals and their behavior is measured as such. These signals are generated/measured by dedicated hardware devices, i.e., arbitrary waveform generators (AWGs) and data acquisition devices/cards (DAQs). A variety of such devices from multiple manufacturers exist.
Hardware abstraction should, first, abstract from the specifics of a device and, second, from the hardware setup (which single device is connected to which qubit) and offer only a uniform set of input and output channels to layers above as well as means to configure devices through a common interface.

**Comment by lumip** [comment]
Might be achieved with the integration of QTLab #11 .

**Comment by terrorfisch** [comment]
We have a hardware abstraction now
