### ISSUE TITLE
Make atomicity an immutable property of PulseTemplate

### ISSUE THREAD

**Issue by terrorfisch** [qutech/qupulse#134]
There are cases where you want to translate f.i. a SequencePulseTemplate or a RepetitionPulseTemplate into a single waveform. Therefore it is useful to make this property not a class like AtomicPulseTemplate but a property that is either

- fixed to be False(i.e. BranchPulseTemplate)
- fixed to be True(i.e. TablePulseTemplate)
- mutable (i.e. SequencePulseTemplate)

**Comment by lumip** [comment]
The is_interruptable property of PulseTemplate is intended to express this (but maybe the name is confusing). It indicates whether or not a PulseTemplate can be split into several waveforms (and therefore execution of it can be interrupted by the Sequencer).
It currently behaves like this:
- fixed to False for TablePulseTemplate, FunctionPulseTemplate
- mutable/creator's choice for SequencePulseTable (given as constructor argument)
- True for BranchPulseTemplate iff subtemplates for both branches are interruptable
- True for LoopPulseTemplate/RepetitionPulseTemplate iff the body subtemplate is interruptable
- True for MultiChannelPulseTemplate iff subtemplates on all channels are interruptable

**Comment by terrorfisch** [comment]
Good point. I thought of the is_interruptable property more as of a hint than a strict order intended for the case that there are parameters that depend on a condition and the translation process needs to be interrupted. The atomicity flag on the other hand indicates that the PulseTemplate always is translated to one waveform.

**Comment by lumip** [comment]
I think that should pretty much amount to the same.

**Comment by terrorfisch** [comment]
```python
class PulseTemplate:
    """Reintroduction of run-time branching would happen here"""
    @abstractmethod
    def _create_program(...):
        pass

class RegularPulseTemplate(PulseTemplate, MeasurementDefiner, ParameterConstrainer):
    """Pulse templates that can be translatred into a single waveform (no runtime stuff).
    All current pulse templates are subclasses of RegularPulseTemplate. Remove WhileLoopPT"""
    def _create_program(...):
        # validate constraints

        if self._evaluates_to_none(...):
            return

        # handle local measurements

        if self.is_atomic or self in to_single_waveform:
            # build waveform + subtemplate stuff

        else:
            self.__internal_create_program(...)
   
   @abstractmethod
   def build_waveform(...):
        pass

    @abstractmethod
    def get_subtemplate_measurement_windows(...):
        """Collect measurement windows of subtemplates"""

    @abstractmethod
    def validate_subtemplate_parameter_constraints(...):
        """Validate parameter constraints of subtemplates"""

class AtomicWrapperPulseTemplate(RegularPulseTemplate):
    """Forward everything"""
    def is_atomic(self):
        return True

    def __init__(self, pt: RegularPulseTemplate):
        pass

class AtomicPulseTemplate(RegularPulseTemplate):
     def get_subtemplate_measurement_windows(...):
        pass

    def validate_subtemplate_parameter_constraints(...):
        pass
```

**Comment by terrorfisch** [comment]
Solved by `_is_atomic` method for itnernal purposes for now
