### ISSUE TITLE
Implement generic qubit class

### ISSUE THREAD

**Issue by hbluhm** [qutech/qupulse#2]
Task of feature #1 

Generic properties of a qubit:
- ID
- Neighbors (other qubits)
- Available gates (new class to be implemented?, perhaps reference to pulses)

Spin-quibt specific (derived class)
- DC Gate voltage channels (sm name)
- Readout channel (sm name) 
- Control AWG channel.

Some connection to tuning mechanism and resulting information (tune or successor)

**Comment by terrorfisch** [comment]
Out of scope for qupulse now
