### ISSUE TITLE
Examples 9* out of date

### ISSUE THREAD

**Issue by thangleiter** [qutech/qupulse#222]
The first cell of the Detailed Sequencing Walkthrough notebook already uses some deprecated (?) features. This seems mostly centered around `LoopPulseTemplate`. Moreover, importing `SoftwareCondition` works only as 
```python
from qctoolkit.pulses.conditions import SoftwareCondition
```

**Comment by thangleiter** [comment]
The same goes for Example 98 (also out of date in declaring measurements as far as I can see).

**Comment by terrorfisch** [comment]
All 9* examples do not work or are outdated and are therefore not in the documentation(`doc\source\examples\examples.rst`). I kept them in the repository so one does not have to dig through old commits to find them.

It would be nice if you could make them work.

**Comment by lumip** [comment]
Examples starting with 9* now either have a more up-to-date counterpart in the non-9* examples or are there to document outdated features. "Fixing" them or trying to "make them work" therefore does not really make sense. I propose keeping them for reference purposes but leave them unchanged.
