### ISSUE TITLE
missing error in plotting

### ISSUE THREAD

**Issue by superpostition** [qutech/qupulse#261]
in plotting.py -> render

should throw error if some voltages are not given or if they are of another type than float etc.

**Comment by terrorfisch** [comment]
This does not belong into `render` but into `TablePT`, `PointPT` and maybe `FunctionPT.build_waveform`. However such checks can be costly for huge pulses.

**Comment by lumip** [comment]
When does this occur? TablePT and PointPT should have such checks in place afaik.. can you maybe provide an example of when erroneous (missing, mistyped) voltages are occuring?

**Comment by lumip** [comment]
Update: TablePT performs some checks that given time values make sense (i.e., are in correct order) during construction, PointPT does not (but maybe should), FunctionPT doesn't have to as no values are explicitely specified. Neither of them checks for type errors and I would argue that is not their responsibility in the first place; type checks should not be in productive code but performed by a typechecker such as mypy...
