### ISSUE TITLE
Sequencing Overhaul

### ISSUE THREAD

**Issue by lumip** [qutech/qupulse#286]
The current Sequencer class has turned out to have several limitations, the most important of which is it's inability to update a subset of frequently changing parameters for a PulseTemplate without sequencing the entire PT anew. Since also result of the Sequencer, the intermediate instruction language, and the ability to interrupt the sequencing process using the requires_stop() methods provides little to no benefit for intended use, Sequencer is deemed obsolete.

Instead of using sequencer, we will add interfaces to directly convert PulseTemplate into Programs. The intended changes are:
- Add method ```create_program(parameters, volatile_parameters, measurement_mapping, channel_mapping)``` to PulseTemplate. The arguments parameters, measurement_mapping, channel_mapping are the same as currently given to Sequencer.push() and PulseTemplate.build_sequence(). The additional argument volatile_parameters is a set of parameter names that will/might change during program lifetime. The method outputs a program represented by the Loop class (hardware.programs.Loop).
- Add method ```update_program(parameters)``` to class Loop, which takes a dictionary of parameter values that have changed compared to the initial parameter values during Program construction.

The two above new methods are to entirely replace Sequencer, InstructionBlock and all other instruction 'language' related objects.

- Change Waveform classes such that they are also updatable for a previsouly specified (sub)set of parameters. This will make propagating updates through hardware drivers much easier.

**Comment by lumip** [comment]
Addresses #283 and #284 (at least partially)

**Comment by terrorfisch** [comment]
See #342
