### ISSUE TITLE
Implement Re-parametrization of Pulse Programs

### ISSUE THREAD

**Issue by lumip** [qutech/qupulse#342]
After sequencing a pulse to obtain a program, it is often desirable to change some parameters without starting the entire sequencing again. Ideally this would also be supported by hardware drivers to avoid costly re-uploads of pulses (if possible) to the hardware device.
Task:
Implement a method `update_program(parameters)` to achieve this desired behavior. 

It is currently unclear whether this should be part of the `Loop` class (which is currently not exposed to end-users) or of the `PulseTemplate` class (then taking a `Loop` instance which will be updated as an argument). It could also be conceivable to wrap the `Loop` class in a class `Program` which can expose a clean interface to the user and handle a `Loop` instance internally.

Also depends on changes to parameter management, especially the ability to mark parameters as volatile. Due to that, this issue should be tackled after #280 is completed.

**Comment by terrorfisch** [comment]
As a first step we will implement this for repetition numbers.

1. Add a volantile flag to `Loop.repetition_count`
2. Add an optional `volantile_parameters` to `PulseTemplate.create_program`. Waveforms may not depend on this parameter. (@terrorfisch)
3. Add a standarized interface for this in the AWG driver (@Hylta)
4. Add support for this for
   - Tabor AWG (@Hylta)
   - ZI HDAWG (@terrorfisch)

**Comment by terrorfisch** [comment]
The data acquisition machinery also needs support for this.

**Comment by terrorfisch** [comment]
Was implemented in release 0.5
