### ISSUE TITLE
pip package for qctoolkit

### ISSUE THREAD

**Issue by peendebak** [qutech/qupulse#361]
Can a pip package for qctoolkit be created? The name `qctoolkit` is already taken on pypi, so another name has to be found.

Currently `pip install qctoolkit` installs the wrong package, which is confusing.

**Comment by terrorfisch** [comment]
First step done by renaming to qupulse in #362.

**Comment by terrorfisch** [comment]
I created a pip package: https://pypi.org/project/qupulse/
