### ISSUE TITLE
Rename project to qupulse

### ISSUE THREAD

**Issue by terrorfisch** [qutech/qupulse#362]
There are multiple points against the current name:
- to broad
- already taken on pypi (See #361)
- non-descriptive

**Comment by terrorfisch** [comment]
Brainstorm:
- PuQuEx (Pulses for Quantum Experiments)
- pyquex
- qpulse
- PuDeX (Pulse Description and eXecution)

**Comment by qutech-lab** [comment]
more brainstorm:
- pudel (*pu*lse *d*escription and *e*xecution *l*ibrary / *pu*lse *d*riven (quantum) *e*xperiments *l*ibrary)

@pcerf 
paws is taken already on pypi (qupaws not)

-- lumip

**Comment by terrorfisch** [comment]
I'll start a poll this evening.

**Comment by pcerf** [comment]
- pulser
- pulzar
- quexl (quantum experiment language/library)
- pycontrol
- qucontrol, Qcontrol, qcontrol, qControl
- qwaves, QWaves, qWaves

**Comment by terrorfisch** [comment]
Unfortunately pycontrol, quest and pyquest are already taken.

**Comment by terrorfisch** [comment]
The new name is qupulse - A Quantum  compUting PULse parametrization and SEquencing framework.

**Comment by terrorfisch** [comment]
Difficulties:
 - backward compatible imports
 - serialization needs to actively import missing modules (new issue)

**Comment by terrorfisch** [comment]
Adding a dir qctoolkit with the following `__init__.py`
```python
import sys
import qupulse

sys.modules['qctoolkit'] = qupulse
```
results in
```python
from qctoolkit.pulses import TablePT as qcTable
from qupulse.pulses import TablePT´as quTable
quTablePT is qcTablePT
```
to be false but
```
results in
```python
import qctoolkit.pulses.TablePT
import qupulse.pulse.TablePT
qctoolkit.pulses.TablePT is qupulse.pulse.TablePT
```
to be true.
