### ISSUE TITLE
installation of qupulse fails because of gmpy2

### ISSUE THREAD

**Issue by peendebak** [qutech/qupulse#375]
The `gmpy2` package is not available in binary form on all platforms. On unix without `mpfr` installed the installation fails. 

When installing `qupulse` with pip the `gmpy2` is downloaded automatically, but compilation fails. Can `fractions.Fraction` be made optional? (see commit 7261b0710e76c2f056cc537da01c434922ac7d56)?

**Comment by terrorfisch** [comment]
Good point. I will impolement it as a fallback.

**Comment by terrorfisch** [comment]
Implemented in #378
