### ISSUE TITLE
Specify Release Policy

### ISSUE THREAD

**Issue by lumip** [qutech/qupulse#381]
Since we now have an official pypi package we should define a policy for releases.
This has to include at least:
- when to release what
- version numbering scheme (im in favor of [semantic versioning](https://semver.org/))
- dealing with deprecation and old feature removal (I don't think we should keep the "support all deprecated features for eternity for backward compatability"-policy)

I'd further propose that "productive" usage of qc-toolkit in the labs also should ideally not rely directly on this repository anymore but on the pypi releases, as this allows for better control over which features are included at what time/in which version.

**Comment by terrorfisch** [comment]
We should also have release notes. Some projects do it via a file that has to be updated with each pull request.

**Comment by lumip** [comment]
I agree, we should have release notes. Sympy apparently just started to use an [automated process for this](https://github.com/sympy/sympy-bot) where release notes are pulled from pull requests, which is interesting but I guess also highly optional for us now. A file should do for our current scope.
I think we could follow sympy's hints on [what makes a good release notes entry](https://github.com/sympy/sympy/wiki/Writing-Release-Notes#what-makes-a-good-release-notes-entry) for this.

**Comment by lumip** [comment]
We cannot change published releases when a dependency gets an update that is incompatible but we need to make sure they still install correctly. The only way to do this is to have reasonable upper bounds for the version.. I grant you that fixing the upper bound to the exact current version of the dependency is probably overzealous but we should at the very least not allow a major version upgrade, probably not even a minor version one (i.e. in the above example restrict xyz<1.4 (or at least xyz<2)).

This blog post also argues in favor of this (and it's not the only one) https://blog.miguelgrinberg.com/post/the-package-dependency-blues

**Comment by terrorfisch** [comment]
We settled with defining certain package versions in the `requirements.txt` that we test against while allowing all versions in `setup.py` unless there is a specific reason not to.
