### ISSUE TITLE
AtomicMultiChannelPulseTemplate does not work with sequenced pulses

### ISSUE THREAD

**Issue by eendebakpt** [qutech/qupulse#398]
How can one create multi-channels pulses from sequenced pulses?

The SequencePT seems to remove to atomicity. The following minimal example fails with a `TypeError: Non atomic subtemplate`
```
from qupulse.pulses import TablePT, SequencePT, AtomicMultiChannelPT

wave1 = TablePT({'0': [(0,0), (10, 1), (20,2), (30,0), (100,0)]})
wave2 = TablePT({'1': [(0,0), (10, 1), (20,2), (30,0), (100,0)]})

wave2a = TablePT({'1': [(0,0), (10, 1), (20,2), (30,0)]})
wave2b = TablePT({'1': [(0,0), (70,0)]})

combined=AtomicMultiChannelPT(wave1, wave2) # works

wave2=SequencePT(wave2a, wave2b)

combined=AtomicMultiChannelPT(wave1, wave2) # fails
```

@lucblom @terrorfisch

**Comment by lumip** [comment]
This is currently due to simplicity reasons. Allowing to create `AtomicMultiChannelPulseTemplate` from arbitrary subtemplates is a bit difficult to implement so we have only implemented it for atomic PTs at the moment.

**Comment by eendebakpt** [comment]
@terrorfisch Thanks for the reply. The `concatenate` works for me.
