### ISSUE TITLE
duration calulation comparision fails for combined pulses

### ISSUE THREAD

**Issue by eendebakpt** [qutech/qupulse#401]
When combining two templates in `AtomicMultiChannelPulseTemplate.__init__` I get the following error message:
```
ValueError: Could not assert duration equality of 11100647.5000000 and 11100647.5000000
```
The first template I created directly, the other is a concatenation of multiple templates.

The numbers in the error message appear equal, so I investigated.
```
ipdb> duration
Expression('11100647.5000000')

ipdb> subtemplate.duration
Expression('11100647.5000000')

ipdb> type(duration)
<class 'qupulse.expressions.ExpressionScalar'>

ipdb> float(duration)==float(subtemplate.duration)
True

ipdb> duration._sympified_expression._mpf_
(0, mpz(5959614747115521), -29, 53)

ipdb> subtemplate.duration._sympified_expression._mpf_
(0, mpz(22201295), -1, 25)
```
The comparison that fails is this one: https://github.com/qutech/qupulse/blob/master/qupulse/expressions.py#L269

It looks like the equality check for an `ExpressionScalar` fails for number which are _almost_ identical, except for some finite precision rounding errors. For the comparison of the `duration` of pulses I think the comparison should be less strict.

@terrorfisch

**Comment by lumip** [comment]
@terrorfisch 
It seems that the `==` equality operator in sympy does test for exact structural(/syntactical) equality, not for mathematical equality \[1\], so maybe we shouldn't be using it when comparing expressions where we are more interested in whether they evaluate to the same result.

We should consider rewriting the `__eq__` of `Expression` as
```
return sympy.simplify(self._sympified_expression - self._sympify(other)) == 0
```
or
```
return sympy.Eq(self.sympified_expression, self._sympify(other)).evalf()
```
(or something like that, I don't know what's quite correct here, refer to \[1\] again).

I'm not sure this is going to resolve the rounding problem above, so maybe we additionally need to not check only for exact equality but `diff < epsilon` (but I'd try out the above first).

\[1\] : https://docs.sympy.org/dev/tutorial/gotchas.html#equals-signs

**Comment by terrorfisch** [comment]
@lumip can you resolve this?

I will implement the option to postpone the duration equality check to instantiation: #402

**Comment by terrorfisch** [comment]
@eendebakpt can you check whether #403 fixes your problem?

**Comment by terrorfisch** [comment]
Please reopen if it doesn't.
