### ISSUE TITLE
Multiple branches for BranchPulseTemplate

### ISSUE THREAD

**Issue by hbluhm** [qutech/qupulse#45]
AWGs typically support branching based on a multi-bit (e.g. 4) digital input signal that is evaluated at certain points. This should eventually also be supported. One option is to extend BranchPulseTemplate to allow multiple branches similar to elif. However, due to hardware restrictions the usage will often be more similar to a C-style switch statement as only the input value rather than arbitrary conditions can be tested. 

This feature is somewhat related to #43 as both controls the autonomous response of hardware to external stimuli.

**Comment by lumip** [comment]
Can you provide some documentation of how exactly this AWG feature works for some concrete device?

**Comment by ekammerloher** [comment]
In this [documentation](http://cp.literature.agilent.com/litweb/pdf/5991-0364EN.pdf) the "Agilent 81180B sequence/segment control Input" is shown in figure 10 page 7. A digital signal controls the waveform flow. More than two possible branches are possible (8-bit / 256 in this case).
<img width="169" alt="screen shot 2015-08-04 at 17 19 14" src="https://cloud.githubusercontent.com/assets/2588233/9064480/feaf0aea-3acc-11e5-99ed-597e2511e6b3.png">

**Comment by hbluhm** [comment]
For BBN APS2, see [documentation]  (http://libaps2.readthedocs.org/en/latest/instruction-set.html). The relevant command is CMP, it seems that the comparison register is an externally supplied signal, i.e. the software side of a connector like the above.  

Tabor WX1284: See "Dynamic Segment / Sequence Control" (p 1-9), "Segment / Sequence Control In" (p 1-17), "Jump event" (p. 3-48), "Using the Dynamic Sequence / Segment Control" (p. 3-49).

Tek AWG: See "AWGControl:EVENt:DJUMp:DEFine" command and related in programming reference. 
The corresponding manuals can be found on our server. 

The basic idea for the latter two is that a 8-10 bit word supplied at an input connector determines the target of the jump in a sequence line.

**Comment by terrorfisch** [comment]
BranchPulseTemplate was removed. This functionality will need to be reintroduced it is required.
