### ISSUE TITLE
Timeline/Scanline Functionality

### ISSUE THREAD

**Issue by lumip** [qutech/qupulse#65]
As a user who intends to perform experiments using the software, I require functionality to setup pulses for the execution of pulses. This includes "queuing" up pulses for each channel, specifying parameters and determining measurement windows (i.e., define scanlines). All this should consider the fact, that parameters might be influenced during the experiment by the evaluation of measurements made so far. Ultimately, the queued pulses must be executed/output by the hardware.

**Comment by terrorfisch** [comment]
This scheduling problem has partly been tackled in Daniel Pimentel's BSc thesis. It is out of scope for qupulse in the current state
