### ISSUE TITLE
Example 03xComposedPulses not reproducible

### ISSUE THREAD

**Issue by Nomos11** [qutech/qupulse#707]
Plot of `second_point_pt` of `PointPT` does not reproduce same behavior (linear voltage decline) as saved in ipynb-file, instead shows constant value. In particular,
```
from qupulse.pulses import PointPT
from qupulse.pulses.plotting import plot
second_point_pt = PointPT([(0, 'v_0+v_1'),
                           ('t_2', 'v_0', 'linear')],
                          channel_names={'A'},
                          measurements={('M', 0, 1)})
parameters = dict(t=3,
                  t_2=2,
                  v_0=1,
                  v_1=1.4)
_ = plot(second_point_pt, parameters, sample_rate=100)
```
outputs plot of constant voltage. (Adding third datapoint restores expected behavior)

**Comment by terrorfisch** [comment]
Thanks for the report! Looks like a regression somewhen after `0.6`. `second_point_pt` is wrongly translated into a `ConstantWaveform`. The error is in `TableWaveform._validate_input`.

**Comment by terrorfisch** [comment]
Error was introduced in 8345423ef44a25f77c0f7213b3298ca2add7f634

I guess this requires a 0.7.1 release.
