### ISSUE TITLE
Functional style helper functions

### ISSUE THREAD

**Issue by terrorfisch** [qutech/qupulse#710]
Similar to #694 and #692 we can add helper methods for "functional" style pulse template creation

```python 
def with_mappings(self, **MappingPTArgs):
    pass

def with_iteration(self, **ForLoopPTArgs):
    pass
```

For easier discoverability all methods start with `with_`.

 - [x] Add `with_parallel_channels`, `with_repetition`, `with_mapping`, `with_iteration`, `with_time_reversal`, `with_appended`
 - [x] Add specializations for optimization
 - [x] Add dedicated helper method paragraph to documentation and improve discoverability.
 - [ x] ~~ Add helper methods to existing examples where applicable~~ Superseeded by #804 
 - [x] Add testing
 - [x] Rename `with_constant_channels` to `with_parallel_channels` since it will allow time dependet expressions in some cases when #704 is merged
 - [x] Add newspiece

**Comment by terrorfisch** [comment]
@BrllsRX Can use these functions in the new examples where applicable? I will do so mysolf over the examples I rework.

**Comment by BrllsRX** [comment]
@terrorfisch Almost all with_funcitons are tested in snake charge scan. No foreseeable problems yet. See details in Task 3 of that example.
