### ISSUE TITLE
Measurement windows not fully ordered in time

### ISSUE THREAD

**Issue by maxbeer99** [qutech/qupulse#780]
I am unsure whether this is intended. When deserializing [this pulse template](https://github.com/qutech/qupulse/files/12357867/6ffbd8f4869d23c63261840a2be4c944.txt) (convert to json first) and doing the following:

```python
pulse_params = {
    't_load': 20316160.0,
    't_read': 15073280.0,
    'T_lambda': 15073280.0,
    'phi_S1': -3.141592653589793,
    'phi_S2': -4.71238898038469,
    'phi_S3': -6.283185307179586,
    'phi_S4': -7.853981633974483,
    'A_1': 0.16,
    'A_2': 0.16,
    'A_3': 0.16,
    'A_4': 0.16,
    'A_m': 0.28,
    'B_1': 0,
    'B_2': 0,
    'B_3': 0,
    'B_4': 0,
    'n': 5
 }

pulse_program = pulse_template.create_program(parameters=pulse_params)
print(pulse_program.get_measurement_windows()["read"])
```

The following output is returned:
```bash
(array([2.26754560e+08, 2.71974400e+08, 4.53509120e+08, 1.11738880e+09,
        5.13802240e+08, 5.74095360e+08, 6.34388480e+08, 6.94681600e+08,
        7.54974720e+08, 8.15267840e+08, 8.75560960e+08, 9.35854080e+08,
        1.17768192e+09, 1.23797504e+09, 1.29826816e+09, 1.35856128e+09,
        1.41885440e+09, 1.47914752e+09, 1.53944064e+09, 1.59973376e+09]),
 array([45219840., 45219840., 45219840., 45219840., 45219840., 45219840.,
        45219840., 45219840., 45219840., 45219840., 45219840., 45219840.,
        45219840., 45219840., 45219840., 45219840., 45219840., 45219840.,
        45219840., 45219840.]))
```

Which indicates that the fourth measurement window actually occurs much later than the following windows.

The question is now, is that list the ultimate authority for which the order of returned measurement results is? i.e. can I just sort this list as well as the results for each window in pairs? Or is this list sorted before the measurement is performed, i.e. the results are already returned in time-order, in which case i would have to sort the measurement window start points alone.

Is this even intended? The vast majority of measurement windows are sorted.

**Comment by terrorfisch** [comment]
Without looking at the details: Could it be that some measurement windows are longer than their pulse templates?

**Comment by BrllsRX** [comment]
> Without looking at the details: Could it be that some measurement windows are longer than their pulse templates?
> 
> From what I remember how the windows are collected the result should be ordered as long as each `Loop`'s windows are fully contained in `[0, loop.duration]`. There is no sorting going on. If you need to sort just do
> 
> ```python
> sorter = np.argsort(begins)
> begins = begins[sorter]
> lengths = lengths[sorter]
> ```

There shouldn't be any measurement window longer than their pulse templates as all measurement windows are defined within corresponding PT. The expression of window length and pulse time interval are literally same.

As you can see in the output of
```print(pulse_program.get_measurement_windows()["read"])```
that was originally posted, ```length``` of all measurement windows are identical without flooring/digital error. Just an exception happens to the forth item whose ```begin``` is 1.11738880e+09 appearing at a wrong place. It suppose to be the 12-th "read" in real time.

**Comment by terrorfisch** [comment]
Upon looking again in the code I need to correct myself: The output of `get_measurement_windows` is not sorted if mutliple levels in the structure define measurement windows.

**Comment by maxbeer99** [comment]
After further investigation it seems like (in this case) that the returned results are in time order which disagrees with the measurement windows. Sorting the windows manually, which formally disconnects the result order from the returned measurement windows, yields expected results.

**Comment by maxbeer99** [comment]
@terrorfisch This needs to be reopened therefore

**Comment by terrorfisch** [comment]
Why? This is no required behaviour of the function. What do you mean with "formally disconnects the result order from the returned measurement windows"?

There is a combined optimized sorting and conversion function already in `qupulse.utils.performance.py` that can be used by the backend with an appropriate sample rate because this can be an actual bottleneck when there are many measurement windows. Therefore I would like to avoid sorting if it is not necessary. But this also means that the measurement windows are already sorted *and* adjusted to the backend sample rate at some point in the program.

I have the feeling this is a XY problem. What do you actually want to achieve?

**Comment by maxbeer99** [comment]
The Problem is the following:

When having multiple measurements repeated in a single scanline, the measurement results returned can not be differentiated, as they do not contain a timestamp.
The only thing that provides timestamps is `get_measurement_windows`, which does not provide the correct timestamps for the actual measurements, as the actual measurements are returned in time-order. 

This behaviour is fine, if it would be clearly communicated what is in time-order and what is not.

This behaviour also leads to the following situation:

Assume you want to display all results in a scanline vs. the time when they were acquired. You then have to extract the possible acquiring times from `get_measurement_windows` as well as the results with `card.extractNextScanline()`. You then create the timestamp array from the measurement windows as well as extract all results and flatten them from the scanline.
Now you have to sort the time-array manually and separately from the voltage-array. This does not seem the right thing to do, as it formally disconnects the indices of these arrays. But as they were never related anyways, this is correct.

**Comment by terrorfisch** [comment]
`AcquisitionProgram` contains the sorted and sample rate adjusted measurement windows but there is no interface to get them yet.

This should work:


```python
begins, lengths = alazar_card._registered_programs[program_name]._masks[mask_name]
sample_rate = alazar_card._registered_programs[program_name]._sample_rate
begins = begins * sample_rate 
lengths = lengths * sample_rate
```

**Comment by terrorfisch** [comment]
Close in favour of #789 

Please re-open if you disagree
