### ISSUE TITLE
Add convenience padding functionality

### ISSUE THREAD

**Issue by terrorfisch** [qutech/qupulse#801]
This is often required to adhere to external alignment requirements

```python
def pad_to(self, to_new_duration: Union[ExpressionLike, Callable[[Expression], Expression]], pt_kwargs: dict = None):
    current_duration = self.duration
    if callable(to_new_duration):
        new_duration = to_new_duration(current_duration)
    else:
        new_duration = ExpressionScalar(to_new_duration)
    pad_duration = new_duration - current_duration
    if pad_duration == 0:
        return self
    pad_pt = ConstantPT(pad_duration, self.final_values)
    if pt_kwargs:
        return SequencePT(self, pad_pt , **pt_kwargs)
    else:
        return self @ pad_pt

def to_next_multiple(sample_rate: ExpressionLike, quantum: int):
    sample_rate = ExpressionScalar(sample_rate)
    return lambda duration: (duration * sample_rate + (quantum - 1)) // quantum * (quantum / sample_rate)
    
```

Usages

```python
my_pt = ...

# pad to a fixed duration
padded_1 = my_pt.pad_to(1000)

# pad to a fixed sample coun
padded_2 = my_pt.pad_to('sample_rate * 1000')

# pad to the next muliple of 16 samples with a symbolic sample rate
padded_3 = my_pt.pad_to(to_next_multiple('sample_rate', 16))

# pad to the next muliple of 16 samples with a fixed sample rate of 1 GHz
padded_4 = my_pt.pad_to(to_next_multiple(1, 16))
```

 - [x] Implement pad_to
 - [ ] Implement duration utility functions
    - [ ] multiple of
    - [ ] combination of minimum and multiple of
    - ...?

**Comment by terrorfisch** [comment]
@Nomos11 Optinions on the interface?

**Comment by Nomos11** [comment]
Looks like the right way to do it. What I do not fully grasp yet is:
- how is the symbolic sample_rate provided?
- I assume final_values contains the current channel allocations - this does not have to be provided via the pt_kwargs (what would be their usecase then?)?
- does it entail potential disadvantages in program compilation afterwards if it is 'split' into 2 PTs?

One addition to the to_next_multiple might be an optional minimum_sample_count to not go below (e.g. the 192 samples for the Tabor)

**Comment by terrorfisch** [comment]
> how is the symbolic sample_rate provided?

At instantiation time, i.e. in `create_program`.

> pt_kwargs (what would be their usecase then?)

`pt_kwargs` is for all optinal arguments that a `SequencePT` takes, f.i. an identifier or measurement definitions.

> does it entail potential disadvantages in program compilation afterwards if it is 'split' into 2 PTs?

This can be automatically detected later or the resulting PT can be passed as a member of `to_single_waveform`.

**Comment by terrorfisch** [comment]
Implemented in #802

**Comment by terrorfisch** [comment]
It was just an example here but it makes sense to provide it. Could you implement it?

**Comment by Nomos11** [comment]
is #805 suitable?

**Comment by Nomos11** [comment]
the corresponding branch has been merged, if I see it correctly
